web:
  host: 0.0.0.0
  port: 8080

server:
  # 如果你想显示你的服务器连接信息的话，就把下面这个show-info改为true，否则保持不动
  show-info: false
  # 服务器名字
  name: Lanbing233Pixel
  # 服务器地址
  host: S9C.52MC.PRO
  # 这个port只是拿来展示的，如果上面关掉了的话可以不动它
  port: 10187
  # 查询信息实际用的是query这个端口，在server.properties里面有，需要自行设置端口并且把这个功能打开
  query: 10188
  logo: https://s1.imagehub.cc/images/2024/02/18/f713cce95a34a9931bda33b198e71bbb.jpeg # https://www.imagehub.cc/image/1hdlTk
  preview: # 服务器预览部分
    title: 这里是Lanbing233Pixel服务器
    # 预览界面的描述，可以用html书写
    descr: |
      Lanbing233Pixel是一个生电-建筑主题的公益服务器，版本1.20.4-carpet，客户端原版即可，Java-BE互通，玩家们大多都是蓝冰的fans，主要在服里复刻蓝冰的像素小人还有一些建筑。服里还有各位生电服的大佬（划掉）再次坐镇，欢迎大家的加入！
      可爱蓝冰酱的主页：<a href="https://space.bilibili.com/85294317" target="_blank"><u>摸鱼冰</u></a>，IP在蓝冰酱的小群里。

    images: # 服务器的预览图片，你需要把文件丢在images文件夹里面，然后复制文件名在这里
      - 2024-02-02_15.05.52.png
      - 2024-02-10_00.04.07.png