web:  # 网页监听的地址和端口
  host: 0.0.0.0
  port: 8080

server:
  # 是否要显示服务器的地址？如果要显示则把show-info设置为true，否则为false
  show-info: true
  name: EMUnion
  host: localhost
  port: 25565
  logo: https://cdn.bilicdn.tk/gh/Vikutorika/newassets@master/img/Miscellaneous/EMUnion.jpg
  preview:  # 服务器预览部分
    title: 服务器预览
    descr: 服务器描述
    images: # 服务器的预览图，你需要把文件丢入images文件夹，然后在这里填写你的文件名
      - pic01.jpg
      - pic02.jpg
  contact:
    content: |  # 服务器加入页面的内容，使用html格式书写
      <p>Hello World</p>